In [1]:
#Import Necessary Libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler,StandardScaler

df  = pd.read_csv('../datasets/dataset1.csv')     # Read the file
print(df)      

/home/vinoth/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/vinoth/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/tmp/ipykernel_84313/61355013.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93
3  Person5  24.0  Hyderabad   No     85
4  Person1  17.0    Chennai  Yes     98


In [2]:
df.isnull().sum()

Person    0
Age       1
City      0
Bool      0
Marks     0
dtype: int64

In [3]:
print(df['Age'])    # Access Coloumn
print('\n')

print(df.describe())  # Generate descriptive statistics
print('\n')

print(df.shape)                     #representing the dimensionality of the DataFrame
print('\n')

print(df.isnull())                  #Return a boolean same-sized object indicating if the values are NA

0    24.0
1    19.0
2     NaN
3    24.0
4    17.0
Name: Age, dtype: float64


             Age      Marks
count   4.000000   5.000000
mean   21.000000  82.400000
std     3.559026  20.366639
min    17.000000  47.000000
25%    18.500000  85.000000
50%    21.500000  89.000000
75%    24.000000  93.000000
max    24.000000  98.000000


(5, 5)


   Person    Age   City   Bool  Marks
0   False  False  False  False  False
1   False  False  False  False  False
2   False   True  False  False  False
3   False  False  False  False  False
4   False  False  False  False  False


In [4]:
print(df); print('\n')

print(df.head(3))                       # Returns first n rows
print('\n')

print(df.loc[df['City']=='Bangalore'])  # Access a group of rows and columns by label(s) 
print('\n')

print(df.iloc[1,1])                     # Purely integer-location based indexing for selection by position.

    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93
3  Person5  24.0  Hyderabad   No     85
4  Person1  17.0    Chennai  Yes     98


    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93


    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47


19.0


df.groupby - Group DataFrame using a mapper or by a Series of columns.

In [5]:
x = df.groupby(['Bool'])         # Group DataFrame using a mapper or by a Series of columns.
print(x.sum())
print('\n')

print(x['Age'].agg(np.mean))
print('\n')

print(x.get_group('No'))         # Print Rows of a specific group

                     Person   Age                     City  Marks
Bool                                                             
No    Person2Person3Person5  67.0  BangaloreDelhiHyderabad    221
Yes          Person4Person1  17.0            MumbaiChennai    191


Bool
No     22.333333
Yes    17.000000
Name: Age, dtype: float64


    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
3  Person5  24.0  Hyderabad   No     85


/tmp/ipykernel_84313/4171253851.py:5: FutureWarning: The provided callable <function mean at 0x7e09841bc5e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(x['Age'].agg(np.mean))
/tmp/ipykernel_84313/4171253851.py:8: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  print(x.get_group('No'))         # Print Rows of a specific group


#### describe()

Generate descriptive statistics that include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding ``NaN`` values.



In [6]:

df2 = pd.read_csv('../datasets/loans.csv')                 #Reads loans.csv file

In [7]:
print(df1)

NameError: name 'df1' is not defined

In [10]:
print(df2)

KeyError: (1, 2)

In [ ]:
df

### SimpleImputer()
Replace missing values using a descriptive statistic (e.g. mean, median, or
most frequent) along each column, or using a constant value.
    

In [10]:
impute = SimpleImputer(missing_values=np.nan, strategy="mean",fill_value='F')
print(df); print('\n')

data = impute.fit_transform(df['Age'].values.reshape(-1,1))[:,0]
print(data)
type(data)

    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93
3  Person5  24.0  Hyderabad   No     85
4  Person1  17.0    Chennai  Yes     98


[24. 19. 21. 24. 17.]


numpy.ndarray

### get_dummies(<coloumn>)

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

In [9]:
df1 = pd.read_csv('datasets/cars.csv')                  #Reads cars.csv file

new_cars = pd.get_dummies(df1[['Model']])
print(new_cars.to_string())
#print(new_cars)

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cars.csv'

In [ ]:
data = [[12,21,45,32],[33,51,31,20],[16,72,36,51]]
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.transform(data))

MinMaxScaler()
[[0.         0.         1.         0.38709677]
 [1.         0.58823529 0.         0.        ]
 [0.19047619 1.         0.35714286 1.        ]]


In [ ]:
cars = pd.read_csv('datasets/cars.csv')
Vol_data = cars[['Volume']]
Weight_data = cars[['Weight']]

scaler = MinMaxScaler()
stdscaler = StandardScaler()

In [ ]:
MinMaxScaler?

Init signature: MinMaxScaler(feature_range=(0, 1), *, copy=True, clip=False)
Docstring:     
Transform features by scaling each feature to a given range.

This estimator scales and translates each feature individually such
that it is in the given range on the training set, e.g. between
zero and one.

The transformation is given by::

    X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
    X_scaled = X_std * (max - min) + min

where min, max = feature_range.

This transformation is often used as an alternative to zero mean,
unit variance scaling.

`MinMaxScaler` doesn't reduce the effect of outliers, but it linearly
scales them down into a fixed range, where the largest occurring data point
corresponds to the maximum value and the smallest one corresponds to the
minimum value. For an example visualization, refer to :ref:`Compare
MinMaxScaler with other scalers <plot_all_scaling_minmax_scaler_section>`.

Read more in the :ref:`User Guide <preprocessing_scaler>`.

Parameters

In [ ]:
StandardScaler?

Init signature: StandardScaler(*, copy=True, with_mean=True, with_std=True)
Docstring:     
Standardize features by removing the mean and scaling to unit variance.

The standard score of a sample `x` is calculated as:

    z = (x - u) / s

where `u` is the mean of the training samples or zero if `with_mean=False`,
and `s` is the standard deviation of the training samples or one if
`with_std=False`.

Centering and scaling happen independently on each feature by computing
the relevant statistics on the samples in the training set. Mean and
standard deviation are then stored to be used on later data using
:meth:`transform`.

Standardization of a dataset is a common requirement for many
machine learning estimators: they might behave badly if the
individual features do not more or less look like standard normally
distributed data (e.g. Gaussian with 0 mean and unit variance).

For instance many elements used in the objective function of
a learning algorithm (such as the RBF kernel of Suppor

In [ ]:
MinMaxScaler.fit_transform?

Signature: MinMaxScaler.fit_transform(self, X, y=None, **fit_params)
Docstring:
Fit to data, then transform it.

Fits transformer to `X` and `y` with optional parameters `fit_params`
and returns a transformed version of `X`.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input samples.

y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
    Target values (None for unsupervised transformations).

**fit_params : dict
    Additional fit parameters.

Returns
-------
X_new : ndarray array of shape (n_samples, n_features_new)
    Transformed array.
File:      ~/.local/lib/python3.10/site-packages/sklearn/base.py
Type:      function

In [ ]:
StandardScaler.fit_transform?

Signature: StandardScaler.fit_transform(self, X, y=None, **fit_params)
Docstring:
Fit to data, then transform it.

Fits transformer to `X` and `y` with optional parameters `fit_params`
and returns a transformed version of `X`.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input samples.

y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
    Target values (None for unsupervised transformations).

**fit_params : dict
    Additional fit parameters.

Returns
-------
X_new : ndarray array of shape (n_samples, n_features_new)
    Transformed array.
File:      ~/.local/lib/python3.10/site-packages/sklearn/base.py
Type:      function

In [ ]:

scaler.fit(Vol_data)
mm_data_vol = scaler.transform(Vol_data)
print(mm_data_vol)
print('\n')

scaler.fit(Weight_data)
mm_data_weight = scaler.transform(Weight_data)
print(mm_data_weight)
print('\n')

stdscaler.fit(Vol_data)
stddata_vol = stdscaler.transform(Vol_data)
print(stddata_vol)
print('\n')

stdscaler.fit(Weight_data)
stddata_weight = stdscaler.transform(Weight_data)
print(stddata_weight)

[[0.0625]
 [0.1875]
 [0.0625]
 [0.    ]
 [0.375 ]
 [0.0625]
 [0.3125]
 [0.375 ]
 [0.375 ]
 [0.4375]
 [0.125 ]
 [0.25  ]
 [0.0625]
 [0.4375]
 [0.4375]
 [0.4375]
 [0.4375]
 [0.8125]
 [0.4375]
 [0.6875]
 [0.4375]
 [0.6875]
 [0.75  ]
 [0.4375]
 [0.6875]
 [0.375 ]
 [0.6875]
 [0.6875]
 [0.4375]
 [0.6875]
 [0.75  ]
 [0.6875]
 [0.4375]
 [0.4375]
 [0.4375]
 [1.    ]]


[[0.        ]
 [0.38702929]
 [0.14539749]
 [0.07845188]
 [0.36610879]
 [0.14539749]
 [0.33368201]
 [0.60146444]
 [0.33682008]
 [0.37656904]
 [0.19874477]
 [0.20920502]
 [0.33682008]
 [0.4832636 ]
 [0.56066946]
 [0.56485356]
 [0.60146444]
 [0.5125523 ]
 [0.34414226]
 [0.56276151]
 [0.83054393]
 [0.66736402]
 [0.60146444]
 [0.65376569]
 [0.65376569]
 [0.70606695]
 [0.73221757]
 [0.97803347]
 [0.7667364 ]
 [0.95711297]
 [0.85251046]
 [1.        ]
 [0.46548117]
 [0.62761506]
 [0.64330544]
 [0.63284519]]


[[-1.59336644]
 [-1.07190106]
 [-1.59336644]
 [-1.85409913]
 [-0.28970299]
 [-1.59336644]
 [-0.55043568]
 [-0.28970299]
 [-0.28970