In [87]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, FunctionTransformer, StandardScaler, LabelEncoder

In [69]:
df  = pd.read_csv('datasets/dataset1.csv')     # Read t]]
print(df)

    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93
3  Person5  24.0  Hyderabad   No     85
4  Person1  17.0    Chennai  Yes     98


In [85]:
x = df.groupby(['Bool'])
print(x.sum().reset_index())
print('\n')
print(x['Age'].agg(np.mean))
print('\n')
print(x.get_group('No'))

  Bool                 Person   Age                     City  Marks
0   No  Person2Person3Person5  67.0  BangaloreDelhiHyderabad    221
1  Yes         Person4Person1  17.0            MumbaiChennai    191


Bool
No     22.333333
Yes    17.000000
Name: Age, dtype: float64


    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
3  Person5  24.0  Hyderabad   No     85


/tmp/ipykernel_82627/293034954.py:4: FutureWarning: The provided callable <function mean at 0x7c0d84506200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(x['Age'].agg(np.mean))
/tmp/ipykernel_82627/293034954.py:6: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  print(x.get_group('No'))


In [70]:
df.head(5)

Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93
3  Person5  24.0  Hyderabad   No     85
4  Person1  17.0    Chennai  Yes     98

In [73]:
df.loc[df['City']=='Bangalore']

Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47

In [74]:
df.loc[df['City']=='Bangalore']

Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47

In [75]:
df.iloc[2:3,2]

2    Mumbai
Name: City, dtype: object

In [76]:
df['Age']

0    24.0
1    19.0
2     NaN
3    24.0
4    17.0
Name: Age, dtype: float64

#### describe()

Generate descriptive statistics that include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding ``NaN`` values.



In [77]:
df.describe()  # Generate descriptive statistics

Age      Marks
count   4.000000   5.000000
mean   21.000000  82.400000
std     3.559026  20.366639
min    17.000000  47.000000
25%    18.500000  85.000000
50%    21.500000  89.000000
75%    24.000000  93.000000
max    24.000000  98.000000

In [ ]:
print(df.shape)                     #representing the dimensionality of the DataFrame

print(df.isnull())                  #Return a boolean same-sized object indicating if the values are NA

(5, 5)
   Person    Age   City   Bool  Marks
0   False  False  False  False  False
1   False  False  False  False  False
2   False   True  False  False  False
3   False  False  False  False  False
4   False  False  False  False  False


In [81]:
df1 = pd.read_csv('datasets/cars.csv')                  #Reads cars.csv file
df2 = pd.read_csv('datasets/loans.csv')                 #Reads loans.csv file

In [82]:
print(df1)

           Car       Model  Volume  Weight  CO2  Unnamed: 5
0       Toyota        Aygo    1000     790   99         NaN
1   Mitsubishi  Space Star    1200    1160   95         NaN
2        Skoda      Citigo    1000     929   95         NaN
3         Fiat         500     900     865   90         NaN
4         Mini      Cooper    1500    1140  105         NaN
5           VW         Up!    1000     929  105         NaN
6        Skoda       Fabia    1400    1109   90         NaN
7     Mercedes     A-Class    1500    1365   92         NaN
8         Ford      Fiesta    1500    1112   98         NaN
9         Audi          A1    1600    1150   99         NaN
10     Hyundai         I20    1100     980   99         NaN
11      Suzuki       Swift    1300     990  101         NaN
12        Ford      Fiesta    1000    1112   99         NaN
13       Honda       Civic    1600    1252   94         NaN
14      Hundai         I30    1600    1326   97         NaN
15        Opel       Astra    1600    13

In [83]:
print(df2)

     client_id loan_type  loan_amount  repaid  loan_id  loan_start  \
0        46109      home        13672       0    10243  2002-04-16   
1        46109    credit         9794       0    10984  2003-10-21   
2        46109      home        12734       1    10990  2006-02-01   
3        46109      cash        12518       1    10596  2010-12-08   
4        46109    credit        14049       1    11415  2010-07-07   
..         ...       ...          ...     ...      ...         ...   
438      26945     other        12963       0    10330  2001-11-26   
439      26945    credit         1728       1    10248  2004-01-27   
440      26945     other         9329       0    10154  2001-12-17   
441      26945      home         4197       0    10333  2003-10-16   
442      26945      home         3643       0    11434  2010-03-24   

       loan_end  rate  
0    2003-12-20  2.15  
1    2005-07-17  1.25  
2    2007-07-05  0.68  
3    2013-05-05  1.24  
4    2012-05-21  3.13  
..          ...

### SimpleImputer()
Replace missing values using a descriptive statistic (e.g. mean, median, or
most frequent) along each column, or using a constant value.
    

In [84]:
impute = SimpleImputer(missing_values="NaN", strategy="mean")
print(df)
imputer = impute.fit(df)   
data = imputer.transform(df)
print(data)

    Person   Age       City Bool  Marks
0  Person2  24.0  Bangalore   No     47
1  Person3  19.0      Delhi   No     89
2  Person4   NaN     Mumbai  Yes     93
3  Person5  24.0  Hyderabad   No     85
4  Person1  17.0    Chennai  Yes     98


ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'Person2'

### get_dummies(<coloumn>)

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

In [ ]:
new_cars = pd.get_dummies(df1[['Model']])
print(new_cars.to_string())
#print(new_cars)

    Model_1  Model_2  Model_3  Model_5  Model_500  Model_A-Class  Model_A1  Model_A4  Model_A6  Model_Astra  Model_Aygo  Model_B-Max  Model_C-Class  Model_CLA  Model_Citigo  Model_Civic  Model_Cooper  Model_E-Class  Model_Fabia  Model_Fiesta  Model_Focus  Model_I20  Model_I30  Model_Insignia  Model_Mondeo  Model_Octavia  Model_Rapid  Model_S60  Model_SLK  Model_Space Star  Model_Swift  Model_Up!  Model_V70  Model_XC70  Model_Zafira
0     False    False    False    False      False          False     False     False     False        False        True        False          False      False         False        False         False          False        False         False        False      False      False           False         False          False        False      False      False             False        False      False      False       False         False
1     False    False    False    False      False          False     False     False     False        False       False        F

In [89]:
data = [[12,21,45,32],[33,51,31,20],[16,72,36,51]]
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.transform(data))

MinMaxScaler()
[[0.         0.         1.         0.38709677]
 [1.         0.58823529 0.         0.        ]
 [0.19047619 1.         0.35714286 1.        ]]


In [90]:
cars = pd.read_csv('datasets/cars.csv')
Vol_data = cars[['Volume']]
Weight_data = cars[['Weight']]

scaler = MinMaxScaler()
stdscaler = StandardScaler()

scaler.fit(Vol_data)
mm_data_vol = scaler.transform(Vol_data)
print(mm_data_vol)
print('\n')

scaler.fit(Weight_data)
mm_data_weight = scaler.transform(Weight_data)
print(mm_data_weight)
print('\n')

stdscaler.fit(Vol_data)
stddata_vol = stdscaler.transform(Vol_data)
print(stddata_vol)
print('\n')

stdscaler.fit(Weight_data)
stddata_weight = stdscaler.transform(Weight_data)
print(stddata_weight)

[[0.0625]
 [0.1875]
 [0.0625]
 [0.    ]
 [0.375 ]
 [0.0625]
 [0.3125]
 [0.375 ]
 [0.375 ]
 [0.4375]
 [0.125 ]
 [0.25  ]
 [0.0625]
 [0.4375]
 [0.4375]
 [0.4375]
 [0.4375]
 [0.8125]
 [0.4375]
 [0.6875]
 [0.4375]
 [0.6875]
 [0.75  ]
 [0.4375]
 [0.6875]
 [0.375 ]
 [0.6875]
 [0.6875]
 [0.4375]
 [0.6875]
 [0.75  ]
 [0.6875]
 [0.4375]
 [0.4375]
 [0.4375]
 [1.    ]]


[[0.        ]
 [0.38702929]
 [0.14539749]
 [0.07845188]
 [0.36610879]
 [0.14539749]
 [0.33368201]
 [0.60146444]
 [0.33682008]
 [0.37656904]
 [0.19874477]
 [0.20920502]
 [0.33682008]
 [0.4832636 ]
 [0.56066946]
 [0.56485356]
 [0.60146444]
 [0.5125523 ]
 [0.34414226]
 [0.56276151]
 [0.83054393]
 [0.66736402]
 [0.60146444]
 [0.65376569]
 [0.65376569]
 [0.70606695]
 [0.73221757]
 [0.97803347]
 [0.7667364 ]
 [0.95711297]
 [0.85251046]
 [1.        ]
 [0.46548117]
 [0.62761506]
 [0.64330544]
 [0.63284519]]


[[-1.59336644]
 [-1.07190106]
 [-1.59336644]
 [-1.85409913]
 [-0.28970299]
 [-1.59336644]
 [-0.55043568]
 [-0.28970299]
 [-0.28970